### PR TITLE
Potentially catastrophic pull request

### PR DESCRIPTION
**Pull request by James0199**
Do not do this, will fuck your code

### CODE REVIEW

**Comment by James0199** [comment]
damn i should rename it to squares.txt instead of squares.py

**Comment by patelheet30** [comment]
Why does this have a won't fix tag 😭

**Comment by patelheet30** [comment]
NONONO. Please don't do any merging or any code yet 🙏

**Comment by James0199** [comment]
yes ok but it does say here that
this branch has no conflicts with the base branch
so idk whats that about

**Comment by James0199** [comment]
aight

**Pull request closed without merging**
